language: go
go: 
 - tip
before_install:
 - go get github.com/axw/gocov/gocov
 - go get github.com/mattn/goveralls
 - go get golang.org/x/tools/cmd/cover
script:
 - go install -a -race std
 - export PATH=$HOME/gopath/bin:$PATH
 - go test -v
 - ./scripts/cover.sh
 - ./scripts/dredd.sh
after_success:
 - curl -H "Content-Type: application/json" --data '{"build": true}' -X POST "https://registry.hub.docker.com/u/silverwyrda/contact/trigger/$DOCKERHUB_TOKEN/"
